### PR TITLE
Created quick links page and navbar integration for homepage and others

### PR DESCRIPTION
**Pull request by Joshua024**

### CODE REVIEW

**Comment by Aranwaolu** [comment]
please, raise the PR from a different branch using the naming convention: "dev-", e.g - "dev-quicklinks". this will help me know what the changes are and what to look for, and so the code doesn't break

**Comment by Joshua024** [comment]
Dear Sir,

My project is already on a new branch called update1 but if you still want
me to go ahead and change the new branch from update1 to anything else; do
let me know sir.

Best regards,

Joshua C. Adumchimma
Lagos, Nigeria
Mobile: 08066590156,
Email: ***@***.***

**Comment by Aranwaolu** [comment]
Please change the name of the branch, and raise a new PR

**Comment by Joshua024** [comment]
Done.
Branch name update1 changed to Dev-quicklinks.

Best regards,

Joshua C. Adumchimma
Lagos, Nigeria
Mobile: 08066590156,
Email: ***@***.***

**Pull request closed without merging**
